DELETE
FROM BOOK_AUTHOR;

INSERT INTO BOOK_AUTHOR (book, author)
VALUES (1, 1);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (2, 2);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (3, 3);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (4, 4);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (5, 5);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (6, 6);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (7, 7);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (8, 8);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (9, 9);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (10, 10);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (11, 9);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (11, 11);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (12, 12);
INSERT INTO BOOK_AUTHOR (book, author)
VALUES (12, 13);