CREATE TABLE IF NOT EXISTS AUTHOR (
    id IDENTITY,
    name VARCHAR(25) NOT NULL,
    surname VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK (
    id IDENTITY,
    title VARCHAR(50) NOT NULL,
    genre VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK_AUTHOR (
    book BIGINT NOT NULL,
    author BIGINT NOT NULL
);

ALTER TABLE BOOK_AUTHOR ADD FOREIGN KEY (book) REFERENCES BOOK(id);
ALTER TABLE BOOK_AUTHOR ADD FOREIGN KEY (author) REFERENCES AUTHOR(id);

CREATE TABLE IF NOT EXISTS REVIEW (
    id IDENTITY,
    reviewerName VARCHAR(50) NOT NULL,
    rating INTEGER NOT NULL,
    book BIGINT NOT NULL
);

ALTER TABLE REVIEW ADD FOREIGN KEY (book) REFERENCES BOOK(id);

